chore(ci): change aws cli install method

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,9 +6,6 @@
 
 version: 2.1
 
-orbs:
-  aws-cli: circleci/aws-cli@1.4.1
-
 defaults: &defaults
   working_directory: ~/repo
   docker:
@@ -46,6 +43,45 @@ deploy_cache: &deploy_cache
 yarn_install: &yarn_install
   name: Install Dependencies
   command: yarn install --frozen-lockfile --non-interactive
+
+commands:
+  install_aws_tools:
+    description: |
+      Install the AWS CLI via pip.
+    steps:
+      - run:
+          name: Install Python and Pip
+          command: |
+            sudo apt-get -y -qq install python3.5-dev
+            sudo curl -O https://bootstrap.pypa.io/get-pip.py
+            sudo python3.5 get-pip.py
+      - run:
+          name: Install AWS and AWS EB CLIs
+          command: |
+            export PIP=$(which pip pip3 | head -1)
+            if [[ -n $PIP ]]; then
+              if which sudo > /dev/null; then
+                sudo $PIP install awscli awsebcli --upgrade
+              else
+                # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+                $PIP install aws --upgrade --user
+              fi
+            elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+              cd
+              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+              unzip awscli-bundle.zip
+              if which sudo > /dev/null; then
+                sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+              else
+                # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+                awscli-bundle/install -b ~/bin/aws
+              fi
+              rm -rf awscli-bundle*
+              cd -
+            else
+              echo "Unable to install AWS CLI. Please install pip."
+              exit 1
+            fi
 
 jobs:
   install:
@@ -132,8 +168,7 @@ jobs:
       - checkout
       - attach_workspace:
           at: ~/project/repo
-      - aws-cli/install:
-          version: '2'
+      - install_aws_tools
       - restore_cache:
           <<: *deploy_cache
       - run:
